#//+------------------------------------------------------------------+
#//|                           VerysVeryInc.Python3.Django.Setting.py |
#//|                  Copyright(c) 2018, VerysVery Inc. & Yoshio.Mr24 |
#//|                 https://github.com/MatsuoStation/Python3.Django/ |
#//|                                                 Since:2018.03.05 |
#//|                                Released under the Apache license |
#//|                       https://opensource.org/licenses/Apache-2.0 |
#//|    "VsV.Python3.Django.Setting.py - Ver.3.7.7 Update:2018.03.17" |
#//+------------------------------------------------------------------+
#//|                                           https://qiita.com/aion |
#//|               https://qiita.com/aion/items/ca375efac5b90deed382/ |
#//+------------------------------------------------------------------+
#//|                                        yuhei (id:yuheiomori0718) |
#//|                http://y0m0r.hateblo.jp/entry/20130403/1365000970 |
#//+------------------------------------------------------------------+
"""
Django settings for Devs project.

Generated by 'django-admin startproject' using Django 1.11.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '9ul)x)x8m(0vq4+v(u1%s0jjc9(ammz)b8+n*!hzcb%d&)$0m@'

# SECURITY WARNING: don't run with debug turned on in production!
### MatsuoStation.Com ###
DEBUG = False
# DEBUG = True

### MatsuoStation.Com ###
ALLOWED_HOSTS = ['dev.matsuostation.com', '.compute-1.amazonaws.com', '127.0.0.1']
# ALLOWED_HOSTS = []


# Application definition
### MatsuoStation.Com ###
import sys
sys.path.insert(0, os.path.join(BASE_DIR, 'Projects'))

NUMBER_GROUPING = 3
# USE_THOUSAND_SEPARATOR = True

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    ### MatsuoStaion.Com ###
    'django.contrib.humanize',              # 1,000
    'bootstrap4',                           # django-bootstrap4
    'Finance.apps.FinanceConfig',           # Finance/
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

### MatsuoStation.Com ###
ROOT_URLCONF = 'config.urls'
# ROOT_URLCONF = 'Devs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # 'DIRS': [],
        'DIRS': [
                    os.path.join(BASE_DIR, 'templates'),
                    # os.path.join(BASE_DIR, 'templatestags'),
                ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'builtins': [
                # os.path.join(BASE_DIR, 'templatetags'),
            ],
        },
    },
]

### MatsuoStaton.Com ###
WSGI_APPLICATION = 'config.wsgi.application'
# WSGI_APPLICATION = 'Devs.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

### MatsuoStation.Com ###
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'OPTIONS': {
            'read_default_file' : '../../ssh/AWS_RDS_Dev.cnf',
            # 'init_command'      : 'SET foreign_key_checks = 0;',
        },
    }
}
'''
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}
'''

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

### MatsuoStation.Com ###
LANGUAGE_CODE = 'ja-jp'
# LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tokyo'
# TIME_ZONE = 'UTC'

USE_I18N = True

### MatsuoStation.Com ###
# DATE_FORMAT = [
#    '%Y-%m-%d %H:%M',
# ]

#DATETIME_FORMAT = [
#    '%H:%M',
    # '%Y-%m-%d %H:%M',
#]
# DATE_INPUT_FORMATS = ['%Y/%d/%m']
# USE_L10N = False
USE_L10N = True


USE_TZ = False
# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

### MatsuoStation.Com ###
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
